[pytest]
addopts = -v -ra --html=reporte/reporte.html --self-contained-html --rootdir=.
testpaths = test
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    test_que_fallan: test que estan fallando
    api: pruebas de API